Repository MarlinFirmware/MarlinDocumentation, pull requests merged in 2022-01, with the labels that each got.

#409 Update documentation for support of up to 6 linear axes
  _configuration/configuration.md
Labels: Section: New

#425 Split up G34 documentation
  _gcode/G034-mgc.md
  _gcode/G034-zsaa.md
Labels: Section: G-code

#433 Link to Cura M486 post processing script
  _gcode/M486.md
Labels: Improvement
