Repository MarlinFirmware/MarlinDocumentation, pull requests merged in 2023-12, with the labels that each got.

#528 Is calibration pattern pt 2
  _tools/input_shaping/freq-calibr.html
  assets/images/features/freq-calibr/damping-drawing.png
  assets/images/features/freq-calibr/freq-pattern2.png
  assets/images/features/freq-calibr/frequency-drawing.png
  assets/images/features/freq-calibr/zeta-pattern2.png
Labels: Improvement

#529 Fix dead link in Install PlatformIO Core
  _basics/install_platformio_cli.md
  assets/javascript/custom.js
Labels: Bug / Fix

#530 add LCD_FOR_MELZI images to controllers
  _hardware/controllers.md
  assets/images/hardware/controllers/LCD_FOR_MELZI_back.jpg
  assets/images/hardware/controllers/LCD_FOR_MELZI_back_thumb.jpg
  assets/images/hardware/controllers/LCD_FOR_MELZI_front.jpg
  assets/images/hardware/controllers/LCD_FOR_MELZI_front_thumb.jpg
Labels: Improvement

#531 📝 Update help links
  _basics/reporting_bugs.md
  _development/contributing.md
  _development/feature_request.md
Labels: Improvement

#533 BTT_MINI_12864_V1 => BTT_MINI_12864
  _hardware/controllers.md
  assets/images/hardware/controllers/BTT_MINI_12864_back.jpg
  assets/images/hardware/controllers/BTT_MINI_12864_back_thumb.jpg
  assets/images/hardware/controllers/BTT_MINI_12864_front.jpg
  assets/images/hardware/controllers/BTT_MINI_12864_front_thumb.jpg
Labels: Completing

#534 add a number of additional LCDs
  _hardware/controllers.md
  assets/images/hardware/controllers/ANET_FULL_GRAPHICS_LCD_back.jpg
  assets/images/hardware/controllers/ANET_FULL_GRAPHICS_LCD_back_thumb.jpg
  assets/images/hardware/controllers/ANET_FULL_GRAPHICS_LCD_front.jpg
  assets/images/hardware/controllers/ANET_FULL_GRAPHICS_LCD_front_thumb.jpg
  assets/images/hardware/controllers/CTC_A10S_A13_back.jpg
  assets/images/hardware/controllers/CTC_A10S_A13_back_thumb.jpg
  assets/images/hardware/controllers/CTC_A10S_A13_front.jpg
  assets/images/hardware/controllers/CTC_A10S_A13_front_thumb.jpg
  assets/images/hardware/controllers/MKS_LCD12864A_back.jpg
  assets/images/hardware/controllers/MKS_LCD12864A_back_thumb.jpg
  assets/images/hardware/controllers/MKS_LCD12864A_front.jpg
  assets/images/hardware/controllers/MKS_LCD12864A_front_thumb.jpg
  assets/images/hardware/controllers/MKS_LCD12864B_back.jpg
  assets/images/hardware/controllers/MKS_LCD12864B_back_thumb.jpg
  assets/images/hardware/controllers/MKS_LCD12864B_front.jpg
  assets/images/hardware/controllers/MKS_LCD12864B_front_thumb.jpg
Labels: Improvement

#491 Updated docs to reflect MPC temp differential tuning
  _features/model_predictive_control.md
  _gcode/M306.md
Labels: Improvement

#535 Add probe location examples
  _gcode/M851.md
Labels: Improvement

#536 Add documentation for T? command
  _gcode/T-mmu2.md
  _gcode/T.md
  _gcode/T001-T002.md
Labels: Completing
