Repository MarlinFirmware/MarlinDocumentation, pull requests merged in 2023-04, with the labels that each got.

#492 M593.md added instructions for Cura
  _gcode/M493.md
  _gcode/M593.md
Labels: Section: How-To, Improvement

#487 Rename "Starting Temperature" to "Ambient Starting Temperature"
  _features/model_predictive_control.md
Labels: Improvement

#496 Add documentation on geometry report
  _gcode/M115.md
Labels: Completing
