Repository MarlinFirmware/MarlinDocumentation, pull requests merged in 2024-07, with the labels that each got.

#567 📝 M600 & M603 are related
  _gcode/M600.md
  _gcode/M603.md
Labels: Completing

#566 📝 Add new boards, complete “since” version
  _data/boards.yml
  _hardware/boards.md
  _includes/boards.md
Labels: Completing

#569 remove duplicate entry boards.yml
  _data/boards.yml
Labels: Bug / Fix

#568 Correct as per #27181
  _features/model_predictive_control.md
Labels: Improvement

#553 Update G042.md with P bool command
  _gcode/G042.md
Labels: Completing

#554 Update M423.md add 'E' parameter
  _gcode/M423.md
Labels: Completing
