Repository MarlinFirmware/MarlinDocumentation, pull requests merged in 2024-08, with the labels that each got.

#560 📝 Drop MPCTEMP's experimental tag
  _gcode/M306.md
Labels: Improvement

#555 Update M401_M402 Deploy/Stow probe, add 'R' parameter
  _gcode/G030.md
  _gcode/M401.md
  _gcode/M402.md
Labels: Completing

#561 Update install_devcontainer_vscode.md
  _basics/install_devcontainer_vscode.md
Labels: Bug / Fix

#562 misc fixes and "improvements"
  _configuration/configuration.md
  _gcode/G000-G001.md
  _gcode/G005.md
  _gcode/G034-zsaa.md
  _gcode/M031.md
  _gcode/M043-T.md
  _gcode/M043.md
  _gcode/M109.md
  _gcode/M149.md
  _gcode/M190.md
  _gcode/M191.md
  _gcode/M193.md
  _gcode/M200.md
  _gcode/M205.md
  _gcode/M207.md
  _gcode/M208.md
  _gcode/M226.md
  _gcode/M404.md
  _gcode/M407.md
  _gcode/M600.md
  _gcode/M906.md
  _gcode/M907.md
  _gcode/M909.md
  _gcode/T-mmu2.md
Labels: Improvement

#556 Update M421.md, from int to index
  _gcode/M421.md
Labels: Improvement

#557 Update M871.md
  _gcode/M871.md
Labels: Improvement

#570 🩹 Fix responsive behavior on narrow screens
  _layouts/default.html
  _sass/_custom.scss
Labels: Bug / Fix, Improvement

#564 NONLINEAR_EXTRUSION Clarify that unretractions are not corrected
  _gcode/M592.md
Labels: Improvement

#571 📝 Update TMC capabilities
  _hardware/tmc_drivers.md
Labels: Completing

#572 📝 Update M115
  _gcode/M115.md
Labels: Completing

#576 📝 Update Discord links
  _basics/install_platformio_vscode.md
  _basics/reporting_bugs.md
  _config.yml
  _configuration/config-ini.md
  _development/contributing.md
  _meta/releases.html
  index.html
Labels: Completing

#578 Update M600.md
  _gcode/M600.md
  _gcode/M603.md
Labels: Bug / Fix
